Provide a minimum micro version for DOVECOT_PREREQ
Otherwise the build fails with Dovecot 2.3.18:
```
fts-elastic-plugin.h:40:50: error: macro "DOVECOT_PREREQ" requires 3
arguments, but only 2 given
   40 | #if defined(DOVECOT_PREREQ) && DOVECOT_PREREQ(2,3)
```

https://doc.dovecot.org/developer_manual/design/plugins/#versioning
> + lib: DOVECOT_PREREQ() - Add micro version which enables compiling
>   external plugins against different versions of Dovecot.

Zero is used here as the minimum micro version.

Fixes #22.